eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway

  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: servicea
          uri: http://localhost:8080
          predicates:
            - Path=/servicea/**
        - id: serviceb
          uri: http://localhost:8081
          predicates:
            - Path=/serviceb/**

management:
  tracing:
    sampling:
      probability: 1.0